Fix pipeline (#16)

diff --git a/.github/workflows/push.cd.yml b/.github/workflows/push.cd.yml
--- a/.github/workflows/push.cd.yml
+++ b/.github/workflows/push.cd.yml
@@ -13,16 +13,23 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v3
 
+    - name: Authenticate to Google Cloud
+      uses: google-github-actions/auth@v1
+      with:
+        credentials_json: ${{ secrets.GCP_SA_KEY }}
+
     - name: Set up Cloud SDK
       uses: google-github-actions/setup-gcloud@v1
       with:
         project_id: ${{ secrets.GKE_PROJECT_ID }}
-        service_account_key: ${{ secrets.GCP_SA_KEY }}
-        export_default_credentials: true
+        install_components: 'kubectl'
 
-    - name: Configure kubectl
-      run: |
-        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GKE_PROJECT_ID }}
+    - name: Get GKE Credentials
+      uses: google-github-actions/get-gke-credentials@v1
+      with:
+        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
+        location: ${{ secrets.GKE_CLUSTER_ZONE }}
+        project_id: ${{ secrets.GKE_PROJECT_ID }}
 
     - name: Deploy to GKE
       run: |
@@ -33,3 +40,25 @@ jobs:
     - name: Verify Deployment
       run: |
         kubectl rollout status deployment/restfulapi-cd -n restfulapi-cd
+
+    - name: Get Service External IP
+      id: get_external_ip
+      run: |
+        echo "Waiting for the external IP to be assigned..."
+        # Wait until the external IP is assigned, with a timeout of 300 seconds (5 minutes)
+        for i in {1..30}; do
+          EXTERNAL_IP=$(kubectl get svc restfulapi-cd -n restfulapi-cd -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
+          if [ -n "$EXTERNAL_IP" ]; then
+            echo "Service External IP: $EXTERNAL_IP"
+            echo "::set-output name=external_ip::$EXTERNAL_IP"
+            exit 0
+          fi
+          echo "Attempt $i: External IP not assigned yet. Waiting for 10 seconds..."
+          sleep 10
+        done
+        echo "Failed to retrieve the external IP within the expected time."
+        exit 1
+
+    - name: Log External IP
+      run: |
+        echo "The deployed service is available at: http://$(steps.get_external_ip.outputs.external_ip):8080"
